[package]
name = "kvs"
version = "0.1.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = { version = "3.0.10", features = ["derive"] }
structopt = "0.2.18"
[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
